### PR TITLE
Using [NotNull] and 'nameof' operator

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by dougbu** [comment]
:shipit: :smile_cat:

**Comment by rynowak** [comment]
:shipit: from me. Thanks!

**Comment by Eilon** [comment]
:shipit: from me too - @dougbu can you merge?

**Comment by Eilon** [comment]
Actually wait!

**Comment by Eilon** [comment]
The CI is failing because we check for ArgNullExceptions and this no longer throws (because we haven't implemented NotNull :smile: ).

Can we temporarily mark those specific tests as `Skipped`?

**Comment by Eilon** [comment]
```
[00:01:58]    Microsoft.AspNet.Routing.Tests.RouteOptionsTests.ConstraintMap_SettingNullValue_Throws [FAIL]
[00:01:58]       Assert.Throws() Failure
[00:01:58]       Expected: typeof(System.ArgumentNullException)
[00:01:58]       Actual:   (No exception was thrown)
[00:01:58]       Stack Trace:
[00:01:58]          RouteOptionsTests.cs(22,0): at Microsoft.AspNet.Routing.Tests.RouteOptionsTests.ConstraintMap_SettingNullValue_Throws()
[00:01:58] Finished:    Microsoft.AspNet.Routing.Tests
```

**Comment by dougbu** [comment]
@Eilon why do we want tests of `[NotNull]` in these repos?  I completely removed those tests in my similar aspnet/Razor#376 PR.  Was thinking of adding a `null`-test removal commit to what @hishamco has done before pushing.

**Comment by Eilon** [comment]
Oh good point, we can just remove the tests.

**Comment by dougbu** [comment]
merged as 8636477 plus efe39e4 for single test removal

**Pull request merged**
