### PR TITLE
Prefer StringComparison over StringComparer when not using comparers

### PR DESCRIPTION
**Pull request by JamesNK**
https://stackoverflow.com/a/8918112/11829

### CODE REVIEW

**Comment by rynowak** [comment]
The code change seem fine, but I've read that post over a few times and I still don't get it. How does this make user's lives better? Does this more perf?

**Comment by JamesNK** [comment]
There is no real benefit, it's just StringComparer is for cases when an API uses IComparer, e.g. the Dictionary comparer, and StringComparison is for regular string comparisons.

**Comment by rynowak** [comment]
Ok - you get an approve because its clearer? I guess?

**Comment by JamesNK** [comment]
You have forgotten the most valuable thing of all: 1 James point

**Pull request merged**
