### PR TITLE
Get AppVeyor builds working again

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by rynowak** [comment]
I don't know anything about appveyor, but I trust you that this is good so :shipit:

**Comment by dougbu** [comment]
Last successful AppVeyor build was just before upgrade to VS 2017.

**Comment by dougbu** [comment]
@rynowak I know you don't know 😈. That's why I asked for a _specific_ @pranavkm. Some days, a Ryan isn't enough.

**Comment by dougbu** [comment]
Weird. No AppVeyor build was started for this PR.

@natemcmaster did anything change w.r.t. `os: Visual Studio 2017 RC`? Nothing obvious in the skimpy AppVeyor docs and support forums.

**Comment by natemcmaster** [comment]
The default AppVeyor image doesn't have .NET Framework 4.6 which is required for the new test runner. cref https://github.com/Microsoft/vstest/issues/315

**Comment by dougbu** [comment]
@natemcmaster thought it was something like that. My concern was just that, for a while, the AppVeyor check wasn't showing up here.

**Comment by dougbu** [comment]
7c37e31

**Pull request merged**
