### PR TITLE
Fix case sensitive comparison in TemplateMatcher

### PR DESCRIPTION
**Pull request by ajaybhargavb**
https://github.com/aspnet/Routing/issues/210

@pranavkm

### CODE REVIEW

**Comment by Eilon** [comment]
This change looks :shipit: to me, though can we add a unit test? (Make sure the test *fails* without your change.)

Also wondering if we did a scan through the rest of routing to check for various EndsWith/Contains/StartsWith and other string APIs to make sure we pass in the right comparer?

**Comment by ajaybhargavb** [comment]
Already did. Couldn't find any. Will add a unit test.

**Comment by Eilon** [comment]
Ping me when the test is in :smile:

**Comment by ajaybhargavb** [comment]
Spoke in person. No need to add a test because this case is only hit for a period (.)

**Pull request merged**
