### PR TITLE
Add DfaMatcherBuilder benchmarks

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/aspnet/Routing/issues/628

GitHub
```
 Method |     Mean |     Error |    StdDev |  Op/s |    Gen 0 |   Gen 1 | Allocated |
------- |---------:|----------:|----------:|------:|---------:|--------:|----------:|
    Dfa | 2.248 ms | 0.0435 ms | 0.0550 ms | 444.9 | 136.7188 | 50.7813 |   1.55 MB |
```

Azure
```
 Method |     Mean |    Error |   StdDev |  Op/s |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
------- |---------:|---------:|---------:|------:|---------:|---------:|---------:|----------:|
    Dfa | 357.2 ms | 7.020 ms | 6.567 ms | 2.799 | 937.5000 | 875.0000 | 812.5000 | 195.18 MB |
```

### CODE REVIEW

**Comment by rynowak** [comment]
> 195.18 MB

😬

**Comment by rynowak** [comment]
Do you think it's worth adding a case for comparison with like 5 endpoints? We test the startup perf end to end with pretty small websites (techempower), and a typical customer application will be smaller than github.

**Comment by JamesNK** [comment]
Also ~5k of Endpoints for Azure takes 17 megs of memory. 11 megs for the RoutePatterns and 6 megs for the endpoint collection. A lot of the endpoint collection size comes from the internal ConcurrentDictionary.

**Comment by rynowak** [comment]
Do you have a breakdown of what makes `RoutePattern` so big? Is it the strings?

**Comment by JamesNK** [comment]
image

Mostly collections.

**Comment by JamesNK** [comment]
image

**Comment by JamesNK** [comment]
Whoops, brain stopped working and I forgot about the freeze. Reverted.

**Pull request merged**
